name: Build and publish container image (Release)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
      dry-run:
        description: "dry-run: true will never create relase/nuget."
        required: true
        default: false
        type: boolean

env:
  REGISTRY_GHCR: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-container:
    name: Build and Publish
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          tags: type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag }}
          images: ${{ env.REGISTRY_GHCR }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        env:
          DOCKER_BUILD_SUMMARY: false
        with:
          context: .
          file: src/AIApiTracer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.dry-run != 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  publish-executables:
    name: Publish Executables
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      matrix:
        rid: [win-x64, win-arm64, linux-x64, linux-arm64, osx-arm64]
    steps:
      - uses: Cysharp/Actions/.github/actions/checkout@main
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
      - name: Publish Executable
        run:  dotnet publish src/AIApiTracer -r ${{ matrix.rid }} --self-contained -p:PublishSingleFile=true -o ./publish/${{ matrix.rid }}
      - name: Create ZIP file
        run: |
          cd ./publish/${{ matrix.rid }}
          zip -r ../AIApiTracer-${{ matrix.rid }}-${{ inputs.tag }}.zip .
      - uses: Cysharp/Actions/.github/actions/upload-artifact@main
        with:
          name: AIApiTracer-${{ matrix.rid }}-${{ inputs.tag }}
          path: ./publish/AIApiTracer-${{ matrix.rid }}-${{ inputs.tag }}.zip
          retention-days: 1

  create-release:
    needs: [build-container, publish-executables]
    permissions:
      contents: write
    uses: Cysharp/Actions/.github/workflows/create-release.yaml@main
    with:
      commit-id: ''
      dry-run: ${{ inputs.dry-run }}
      tag: ${{ inputs.tag }}
      release-format: '{0}'
      release-upload: true
      release-asset-path: |
          ./AIApiTracer-win-x64-${{ inputs.tag }}/AIApiTracer-win-x64-${{ inputs.tag }}.zip
          ./AIApiTracer-win-arm64-${{ inputs.tag }}/AIApiTracer-win-arm64-${{ inputs.tag }}.zip
          ./AIApiTracer-linux-x64-${{ inputs.tag }}/AIApiTracer-linux-x64-${{ inputs.tag }}.zip
          ./AIApiTracer-linux-arm64-${{ inputs.tag }}/AIApiTracer-linux-arm64-${{ inputs.tag }}.zip
          ./AIApiTracer-osx-arm64-${{ inputs.tag }}/AIApiTracer-osx-arm64-${{ inputs.tag }}.zip
      nuget-push: false
    secrets: inherit
